### ISSUE TITLE
Allow standalone API keys to be created

### ISSUE THREAD

**Issue by jeriox** [ephios-dev/ephios#906] opened 2023-03-08 21:32 UTC
As of #904 users are able to acquire an access token for the API via an OAuth2 flow. This does not suit all usecases, e.g. for a screen that displays upcoming events physically at the site of the organisation as this is not bound to a single user.

To allow this, we want to extend the AccessToken model and allow it to be bound to a group (so that it can inherit permissions from there). We need to implement a custom version of the DjangoObjectPermissions permission class because it currently only checks the permissions of `request.user`, which wouldn't be set in this case. We should also make sure that groups have all neccessary options to produce sensible permission sets (e.g. `view_event` permission globally instead of object-based to allow display of all events).

**Comment by felixrindt** [comment] 2023-07-13 17:41
duplicate of #737

**Closed by felixrindt** 2023-07-13 17:41 UTC
Labels: [P] minor, [C] feature
